version: '3'

services:
  mysql:
    image: percona/percona-server:8.0.17
    container_name: vuejs-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=vue-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - TZ=Europe/Moscow
    ports:
      - "3307:3306"
